executors:
  local:
    bash:
      description: submit jobs on local machine using bash shell
      shell: bash

    sh:
      description: submit jobs on local machine using sh shell
      shell: sh

    python:
      description: submit jobs on local machine using python shell
      shell: python
  slurm:
    normal:
      launcher: sbatch
      partition: normal
      pollinterval: 15
config:
  editor: vi
  paths:
    prefix: $SCRATCH/buildtesthome
